name: Update posts from Hashnode RSS (debug)

on:
  workflow_dispatch:
  schedule:
    - cron: '17 6 * * *'   # daily at 06:17 UTC
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch RSS (with debug)
        run: |
          set -euxo pipefail
          RSS_URL="https://forrest.hashnode.dev/rss.xml"   # <-- your feed
          echo "Fetching from: $RSS_URL"

          # Fetch with redirects + browser UA + compression
          curl -A "Mozilla/5.0" -sL --compressed -D headers.txt "$RSS_URL" -o rss.xml

          echo "----- HEADERS -----"
          cat headers.txt || true

          echo "----- FIRST 400 CHARS -----"
          head -c 400 rss.xml || true
          echo
          echo "----- FILE TYPE -----"
          file rss.xml || true

      - name: Generate posts.json
        run: |
          python3 - <<'PY'
          import xml.etree.ElementTree as ET, json, sys
          from datetime import datetime

          try:
              root = ET.parse('rss.xml').getroot()
          except Exception as e:
              print("XML parse failed:", e)
              # Print the first ~800 characters to the log to see what's inside
              try:
                  print(open('rss.xml','rb').read(800).decode('utf-8','replace'))
              except Exception:
                  pass
              sys.exit(1)

          items = []
          for item in root.findall('.//item'):
              title = (item.findtext('title') or '').strip()
              link  = (item.findtext('link') or '').strip()
              pub   = (item.findtext('pubDate') or '').strip()
              try:
                  date = datetime.strptime(pub, '%a, %d %b %Y %H:%M:%S %Z').isoformat()
              except Exception:
                  date = pub
              tags = [c.text.strip() for c in item.findall('category') if c is not None and c.text]
              items.append({'title': title, 'url': link, 'date': date, 'tags': tags})

          items = sorted(items, key=lambda x: x['date'], reverse=True)[:24]
          open('posts.json', 'w').write(json.dumps(items, indent=2))
          print("Wrote posts.json with", len(items), "items")
          PY

      - name: Commit changes
        if: success()
        run: |
          if git diff --quiet posts.json 2>/dev/null; then
            echo "No changes in posts.json"
          else
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add posts.json
            git commit -m "Update posts.json from Hashnode RSS"
            git push
          fi

      - name: Upload rss.xml (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rss-debug
          path: |
            rss.xml
            headers.txt
