name: Update posts from Hashnode (API)

on:
  workflow_dispatch:
  schedule:
    - cron: '17 6 * * *' # daily at 06:17 UTC
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run fetch script
        run: |
          set -euxo pipefail
          python3 scripts/fetch_hashnode.py

      - name: Show file
        run: |
          ls -l
          echo "----- posts.json (first 200 bytes) -----"
          head -c 200 posts.json || true

      - name: Commit posts.json
        run: |
          git config --global user.name "forrestcaffray"
          git config --global user.email "forrestcaffray@users.noreply.github.com"
          git add posts.json
          git commit -m "Update posts.json" || echo "No changes to commit"
          git push
