name: Update posts from Hashnode (API)

on:
  workflow_dispatch:
  schedule:
    - cron: '17 6 * * *'
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run fetch script
        run: |
          set -euxo pipefail
          python3 scripts/fetch_hashnode.py

      - name: Show file
        run: |
          ls -l
          echo "----- posts.json (first 200 bytes) -----"
          head -c 200 posts.json || true
          echo

      - name: Commit posts.json
        run: |
          set -euxo pipefail
          if [ -f posts.json ]; then
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add posts.json
            git commit -m "Update posts.json from Hashnode API" || echo "Nothing to commit"
            git push || true
          else
            echo "posts.json not found" >&2
            exit 1
